---
- name: Ensure the application directory exists and is writable
  stat: path=/dry
  register: app_path

- name: Create the directory for the application code
  file: path=/dry state=directory owner={{ansible_user_id}}
  when: not app_path.stat.exists
  sudo: yes

- name: Ensure the application code exists
  stat: path=/dry/server.js
  register: app_exists

- name: Clone the application code
  git: repo=git@github.com:loganetherton/ac.git dest=/dry update=yes
#  when: not app_exists.stat.exists
  register: app_cloned

- name: Install bower
  npm: global=yes name=bower state=present version='1.3.12'
  sudo: True

- name: Install pm2
  npm: global=yes name=pm2 state=present version='0.12.3'
  sudo: True

# Need to find a way to deal with the interactive prompt
# I don't believe this is updating new packages when they're added
# See: http://marvelley.com/blog/2014/04/23/handling-interactive-ansible-tasks/
- name: Install bower packages
  shell: creates=/dry/bower_components chdir=/dry bower install

- name: Install grunt
  npm: global=yes name=grunt-cli state=present version='0.1.13'
  sudo: True

- name: Install npm packages
  shell: creates=/dry/node_modules chdir=/dry npm install

# See if the application is already running

#- name: Start the app
#  shell: chdir=/dry screen -dSm grunt bash -c "grunt"