---
- name: Configure existing instances
  hosts: app_servers
  remote_user: ubuntu
  roles:
    - system
    - app
    - database


- name: Configure existing instances
  hosts: app_servers
  remote_user: ubuntu
  roles:
    - route53