---
- name: Configure existing instances
  hosts: app_servers
  remote_user: ubuntu
  vars:
      node_version: "0.10.33"
      node_version_tag: "v0.10.33"
      node_prefix: "node-v{{node_version}}"
      node_tarball: "{{node_prefix}}.tar.gz"
      node_path: "/usr/local"
  roles:
#    - system
#    - database
    - node
#    - app