---
- name: Configure existing instances
  hosts: app_servers
  remote_user: ubuntu
  vars:
      node_version: "0.10.33"
      node_version_tag: "v0.10.33"
      node_prefix: "node-v{{node_version}}"
      node_tarball: "{{node_prefix}}.tar.gz"
      node_path: "/usr/local"
  roles:
#    - system
#    - database
#    - node
    - app

#- name: pm2 for app management
#  hosts: app_servers
#  remote_user: ubuntu
#  sudo: true
#  vars:
#      pm2_startup: ubuntu
#      pm2_apps:
#        - /dry/ecosystem.json
#      pm2_service_enabled: yes
#      pm2_service_state: started
## NOTE: The franklinkim.pm2 role is dependent on pm2: https://github.com/weareinteractive/ansible-pm2
#  roles:
#    - franklinkim.pm2