---
- name: Terminate instances
  hosts: app_servers
  user: ubuntu
  tasks:
    # So, this is a separate action from terminate instances below. The variables from it become available
    - name: Get EC2 facts
      ec2_facts:

#    - debug: var=ansible_ec2_instance_id
    - name: Terminating instances
      local_action:
        module: ec2
        state: 'absent'
        region: us-east-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

    - name: Remove ec2 instance from hosts
      local_action: lineinfile dest=inventory/hosts regexp="{{ansible_ec2_public_hostname}}" state=absent
      with_items: ec2.instances


#    - name: Test variables
#      debug: var=ansible_ec2_instance_id

#- name: Something
#  hosts: app_servers
#  user: ubuntu
#  tasks:
#    - name: Get first debug
#      debug: " {{ hostvars['ansible_ec2_ami_manifest_path'] | to_yaml }}"
#    debug: " {{ vars | to_yaml }} "

#    HOSTVARS (ANSIBLE GATHERED, group_vars, host_vars) :
#
#             {{ hostvars['wip-box'] | to_yaml }}
#
#             PLAYBOOK VARS:
#
#             {{ vars | to_yaml }}